class User < ActiveRecord::Base
  has_secure_password

  def authenticate(password)
    # binding.pry
    # Salts generated by generate_salt are always 29 chars long.
    salt = password_digest[0..28]
    hashed = BCrypt::Engine::hash_secret(password, salt)
    if (hashed) == self.password_digest
      self
    else
      nil
    end
  end
end
